# Netlify temel yapılandırma dosyası

[build]
  # Sitenizin yayınlanacağı klasör.
  publish = "public/"
  
  # Sunucusuz fonksiyonlarınızın bulunduğu klasör.
  functions = "netlify/functions/"

# Bu bölüm, fonksiyonların DERLENME ayarlarını içerir.
[functions]
  # Fonksiyonlar için Node.js sürümünü ve paketleyiciyi belirtir.
  node_bundler = "esbuild"

# Not: Zaman aşımı ayarı kaldırıldı. Flash model için varsayılan 10 saniye yeterlidir.
