# Netlify temel yapılandırma dosyası

[build]
  # Sitenizin yayınlanacağı klasör.
  publish = "public/"
  
  # Sunucusuz fonksiyonlarınızın bulunduğu klasör.
  functions = "netlify/functions/"

[functions]
  # Fonksiyonlar için Node.js sürümünü ve paketleyiciyi belirtir.
  node_bundler = "esbuild"
  
  # --- YENİ SATIR BURADA ---
  # Fonksiyonun zaman aşımı süresini 25 saniyeye çıkarır.
  timeout = 25
