# Netlify temel yapılandırma dosyası

[build]
  # Sitenizin yayınlanacağı klasör.
  publish = "public/"
  
  # Sunucusuz fonksiyonlarınızın bulunduğu klasör.
  functions = "netlify/functions/"

# Bu bölüm, fonksiyonların DERLENME ayarlarını içerir.
[functions]
  # Fonksiyonlar için Node.js sürümünü ve paketleyiciyi belirtir.
  node_bundler = "esbuild"

# Bu bölüm, TÜM fonksiyonların (*) ÇALIŞMA ZAMANI ayarlarını içerir.
# Ücretsiz planda bu süre genellikle 10 saniye ile sınırlıdır, 
# ancak bu ayarı eklemek projenin gelecekteki olası ihtiyaçları için iyi bir pratiktir.
[functions."*"]
  timeout = 25
